import { ObjectId } from "mongodb";

export default interface Aircraft {
  _id: ObjectId;
  groupId: ObjectId;
  name: string;
  year: number;
  annualCheckDate: Date;
  vorCheckDate: Date;
  oneHundredHourCheck: number;
  airworthinessDirectives?: AirworthinessDirective[];
  eltCheckDate: Date;
  transponderCheckDate: Date;
  altimeterCheckDate: Date;
}

export interface AirworthinessDirective {
  name: string;
  dateOfCheck?: string;
  dateOfNextCheck?: string;
  hourCheck?: number;
  hourNextCheck?: number;
  isHour: boolean;
}

// on front end: form will contain name field and year field
// -- will NOT include a field for _id or userId
// front end will send a payload that looks like this: {name: "whatever", year: 1992}

// _id (which is an ObjectId) will be generated by Mongo
// automatically when we INSERT into database.

// however, we WILL add the userId to the object that we want to insert.
// the object will then look like this:
// {name: "whatever", year: 1992, userId: 1234534654643646 (whatever - it is an ObjectId)}

// finally, we will insert that object into mongo
